version: "3.9"
services:
  translate:
    image: ghcr.io/lane-fullstack/translate-api:latest
    container_name: translate-api
    environment:
      - GUNICORN_WORKERS=8 # 手动设置为 8 个 workers
    ports:
      - "5050:5050"
    volumes:
      - ./translate-api/models:/app/models
      - ./translate-api/config.yaml:/app/config.yaml:ro
    restart: unless-stopped
